### ISSUE TITLE
Publish vendor nothing

### ISSUE THREAD

**Issue by kevinreytabada** [benwilkins/laravel-fcm-notification#10]
When i run php artisan vendor:publish --provider="Benwilkins\FCM\FcmNotificationServiceProvider" it gives me an error Nothing to publish for tag []. how can i fix this?

**Comment by bedezub** [comment]
I am having the same error, Help!

**Comment by ahmedalkhairy** [comment]
same here
laravel 5.5

**Comment by benwilkins** [comment]
Updated documentation. You no longer need to publish the config. The key comes from `config('services.fcm.key')`

Add your Firebase API Key in config/services.php.

```
return [
   
    ...
    ...
    
    /*
     * Add the Firebase API key
     */
    'key' => ''
];
```
