### ISSUE TITLE
Releases instead of dev-master?

### ISSUE THREAD

**Issue by chimit** [benwilkins/laravel-fcm-notification#35]
Maybe it would be better to make new releases instead of proposing everybody to use the dev-master branch?

**Comment by ankurk91** [comment]
I agree with OP

**Comment by benwilkins** [comment]
There are releases. The readme just doesn't reflect it. I'll update the readme.

**Comment by ankurk91** [comment]
The most recent version v3.0 does not support Laravel 5.8

**Comment by huynhphan89** [comment]
@benwilkins Please bump new version supports Laravel 5.8

**Comment by benwilkins** [comment]
v3.0.1 is released now and supports L5.8
