### ISSUE TITLE
Class mailes does not exist

### ISSUE THREAD

**Issue by 2santos93** [benwilkins/laravel-fcm-notification#42]
Maybe the title has nothing to do with this library, however, I'm going to tell you about a problem I have.

I was using this library and everything was going very well, however today I started generating the following error: "Class mailer does not exist" when I used any command like composer update, after hours searching the internet and not finding any solution. It occurred to me to comment on the last library I had installed (FCM being the last one). By commenting on it in the config / app, any command works. However, I do not understand why.

Thankful that I can help me.

**Comment by railken** [comment]
I have the same problem using laravel 5.6. The cause of the problem is this commit: https://github.com/benwilkins/laravel-fcm-notification/commit/673adf7c5d8e2005b2a3efcd92a5ff9d50978da8

**Comment by WalissonRodrigo** [comment]
I'm using laravel 5.5.4 and before update this package i have this same problem. Class mailer does not exist

**Comment by WalissonRodrigo** [comment]
> I have the same problem using laravel 5.6. The cause of the problem is this commit: [673adf7](https://github.com/benwilkins/laravel-fcm-notification/commit/673adf7c5d8e2005b2a3efcd92a5ff9d50978da8)

I try revert this code in my vendor and solve the problem. This commit **[673adf7]** is the problem.

**Comment by benwilkins** [comment]
I'll look into it, but you can try using version 3.0.0 instead of 3.0.1 if you're on Laravel <5.8.

**Comment by benwilkins** [comment]
I'm on 5.8, and I'm not receiving this error.

**Comment by omacesc** [comment]
I have the same problem in Laravel 5.5, to resolve the problem change to v3.0.0, no works with v3.0.1

**Comment by 2santos93** [comment]
i use Laravel 5.4, and v3.0.0. And I still have the same problem

**Comment by faizanzulfiqar-arpatech** [comment]
Hello I was also having same issue in laravel 5.4 . and it was not fixing by downgrading to 3.0.0.
So i did it by manually Placing old code in FCMNotificationServiceProvider class
Also you need to remove the parameter $notification from routeNotificationForFcm function placed in your model.

Hope it help someone

**Comment by benwilkins** [comment]
Reverting to 3.0.0 should fix this issue. Make sure you are actually using that version by checking your composer lock. If you are and it doesn't fix it, try reverting back to 2.0.2. Note that 2.0.2 will not work with Laravel 5.8.

**Comment by dash8x** [comment]
I was having the same issue on Laravel 5.6. Setting the package version to 3.0.0 in composer.json and running composer install fixed the issue.
