### ISSUE TITLE
Use the same default priority as Firebase

### ISSUE THREAD

**Issue by nicoqh** [benwilkins/laravel-fcm-notification#5]
Firebase notification messages [default to high priority](https://firebase.google.com/docs/cloud-messaging/concept-options#setting-the-priority-of-a-message).

Should this library do the same?

**Comment by thomaswardiii** [comment]
Where does it say this? The priority seems to be dependent upon the type of message and its purpose, not that all of them are high priority for all types of notifications.

**Comment by nicoqh** [comment]
At the time of writing I think this library always included the `notification` key, in which case the message is considered a "notification message" by Firebase and has a high priority by default.

But this is mute now, so I'm closing.
