### ISSUE TITLE
Laravel resolve error

### ISSUE THREAD

**Issue by gildastema** [benwilkins/laravel-fcm-notification#60]
TypeError: Argument 1 passed to Benwilkins/FCM/FcmChannel::__construct() must be an instance of GuzzleHttp/Client, null given, called in /vendor/benwilkins/laravel-fcm-notification/src/FcmNotificationServiceProvider.php on line 22

**Comment by ankurk91** [comment]
How to reproduce this issue?
I never face this issue in Laravel 7
