### ISSUE TITLE
Cannot install the package via Composer

### ISSUE THREAD

**Issue by aminebenkeroum** [benwilkins/laravel-fcm-notification#7]
I could not install the package via Composer: 

`[UnexpectedValueException] Could not parse version constraint @dev-master: Invalid version string "@dev-master"` 

Worked like a charm using : 
`composer require benwilkins/laravel-fcm-notification`

Maybe it's not supported in Composer version 1.2.0

**Comment by nicoqh** [comment]
It's safer to install the package like you did; only a couple of days ago `@dev-master` introduced breaking changes.

Now you're locked down to a specific version and can do a controlled upgrade whenever you want.

That said, if you want the latest version, try:

```
composer require benwilkins/laravel-fcm-notification:dev-master
```

**Comment by preetamhegde** [comment]
I'm facing similar issue. I tried running 'composer require benwilkins/laravel-fcm-notification:dev-master' .I'm getting following error.
Class Illuminate\Notifications\ChannelManager does not exist.
Script php artisan optimize handling the post-update-cmd event returned with error code 1

**Comment by benwilkins** [comment]
Updated documentation. Use version number or leave off version all together to get the latest.

**Comment by preetamhegde** [comment]
Did the same and it worked.
