### ISSUE TITLE
Release 4.0.3 missing on Packagist

### ISSUE THREAD

**Issue by Legoraccio** [benwilkins/laravel-fcm-notification#72]
I don't know how packagist works, so forgive me if the issue is useless.
Is it possible to add the 4.0.3 release to packagist.com?
I am forced to work on dev-master, for production environments it is quite dangerous.

**Comment by Rasoul-Karimi** [comment]
> I don't know how packagist works, so forgive me if the issue is useless.
> Is it possible to add the 4.0.3 release to packagist.com?
> I am forced to work on dev-master, for production environments it is quite dangerous.

i have too this issues with laravel v 8

**Comment by mwllgr** [comment]
Same here:
```
  Problem 1
    - Installation request for laravel/framework (locked at v8.10.0, required as ^8.0) -> satisfiable by laravel/framework[v8.10.0].
    - Conclusion: don't install laravel/framework 5.7.x-dev
    - Installation request for guzzlehttp/guzzle (locked at 7.2.0, required as ^7.0.1) -> satisfiable by guzzlehttp/guzzle[7.2.0].
    - Conclusion: don't install benwilkins/laravel-fcm-notification v4.0.2|install laravel/framework 5.7.x-dev
    - benwilkins/laravel-fcm-notification v4.0.0 requires guzzlehttp/guzzle ^6.2 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - benwilkins/laravel-fcm-notification v4.0.1 requires guzzlehttp/guzzle ^6.2 -> satisfiable by guzzlehttp/guzzle[6.5.x-dev].
    - Conclusion: don't install guzzlehttp/guzzle 6.5.x-dev
    - Installation request for benwilkins/laravel-fcm-notification ^4.0 -> satisfiable by benwilkins/laravel-fcm-notification[v4.0.0, v4.0.1, v4.0.2].
```

**Comment by aaronhuisinga** [comment]
@benwilkins Not sure if you've seen this - but can you please get the latest release tagged on Packagist? Thanks!

**Comment by benwilkins** [comment]
Sorry, I don't know what happened. It should auto-update. I just re-released it and confirmed that it is available on Packagist.
